---
- name: Test oracle-db xe from static
  hosts: oracle_db_ct
  vars:
    oracle_version: xe
    transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-install"
    oracle_images:
      - "linux.x64_11gR2_xe.zip"
  roles:
    - role: ansible-role-oracle-db
  become: True
