---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-oracle-db-12
    shape: large
    image: CentOS7_64-bit
    region: AWS-EUCENTRAL
    wait_timeout: 3600
    groups:
      - rhel_family
      - oracle_db_ct
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../resources/provisioning/create.yml
    prepare: ../resources/provisioning/prepare.yml
    destroy: ../resources/provisioning/destroy.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY: "/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible"
scenario:
  name: cloud-aws-oracle-12-delegated
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
